### ISSUE TITLE
protobuf build error with gcc-7.5

### ISSUE THREAD

**Issue by ScXfjiang** [Oneflow-Inc/oneflow#3086]
**System Info**
Ubuntu 18.04.4 LTS
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CUDA/cuDNN Version: 10.1 / 7.6

**Build Log**
/home/xfjiang/repos/oneflow/third_party/protobuf/include/google/protobuf/map.h:882:29: error: cannot call member function ‘bool google::protobuf::Map<Key, T>::InnerMap::TableEntryIsNonEmptyList(google::protobuf::Map<Key, T>::size_type) const [with Key = std::__cxx11::basic_string<char>; T = oneflow::Feature; google::protobuf::Map<Key, T>::size_type = long unsigned int]’ without object
         if (m_->TableEntryIsNonEmptyList(bucket_index_)) {
         ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
/home/xfjiang/repos/oneflow/third_party/protobuf/include/google/protobuf/map.h:897:24: error: cannot call member function ‘bool google::protobuf::Map<Key, T>::InnerMap::TableEntryIsList(google::protobuf::Map<Key, T>::size_type) const [with Key = std::__cxx11::basic_string<char>; T = oneflow::Feature; google::protobuf::Map<Key, T>::size_type = long unsigned int]’ without object
         return m_->TableEntryIsList(bucket_index_);
         ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
CMake Error at of_ccobj_generated_where_kernel_util.cu.o.cmake:280 (message):
  Error generating file
  /home/xfjiang/repos/oneflow/build/CMakeFiles/of_ccobj.dir/oneflow/customized/kernels/./of_ccobj_generated_where_kernel_util.cu.o


CMakeFiles/of_ccobj.dir/build.make:8043: recipe for target 'CMakeFiles/of_ccobj.dir/oneflow/customized/kernels/of_ccobj_generated_where_kernel_util.cu.o' failed
make[2]: *** [CMakeFiles/of_ccobj.dir/oneflow/customized/kernels/of_ccobj_generated_where_kernel_util.cu.o] Error 1
CMakeFiles/Makefile2:416: recipe for target 'CMakeFiles/of_ccobj.dir/all' failed
make[1]: *** [CMakeFiles/of_ccobj.dir/all] Error 2
Makefile:114: recipe for target 'all' failed
make: *** [all] Error 2

**Solution**
* downgrade gcc-7.5 to gcc-6.5 (also works with gcc-4.8.5)
* or patch third-party protobuf

[Reference: TensorFlow Issue 26155](https://github.com/tensorflow/tensorflow/issues/26155)
